### ISSUE TITLE
请求wine下运行的方案

### ISSUE THREAD

**Issue by poly000** [project-yuki/YUKI#108]
已经在找依赖了
首先把fakechinese整上后
`LC_ALL=C wine YUKI.exe`
添加游戏还是不行

` 0070:err:shell:SHGetFolderPathAndSubDirW Failed to create directory L"C:\\users\\poly\\\684c\9762". `
https://forum.winehq.org/viewtopic.php?t=32657

看起来是wine的bug，但是不清楚所以先挂着

**Comment by tinyAdapter** [comment]
来这边讨论一下吧 https://github.com/project-yuki/planning/issues/10
