### ISSUE TITLE
换行后文本会缺失

### ISSUE THREAD

**Issue by rxia24** [project-yuki/YUKI#11]
如果提取出来的文本有换行的话，换行之后的文本会缺失。
发现于waffle的游戏。
![ss](https://user-images.githubusercontent.com/22437401/60194282-97f74c80-986b-11e9-8fa3-e65b94205907.PNG)

**Comment by Artikash** [comment]
Use Textractor >4.3.0.

**Comment by rxia24** [comment]
I have tried with Textractor 4.3.3, it work fine, it can extract all the text.
Then I copied TextractorCLI.exe and texthook.dll to "YUKI\lib\textractor\", to replace the older one.
But when I opened game by YUKI, the text after line break was still missing.

**Comment by tinyAdapter** [comment]
Seems it's due to a bug of node-textractor. Someone submitted a PR for it, I'm fixing this problem tonight.

**Comment by tinyAdapter** [comment]
I've published a newer version of YUKI, but there is no multiline game in my library, so you can download it and make a test. If the bug still exists, reopen this issue.

**Comment by rxia24** [comment]
It support multiline game indeed, but other bug appeared.
Text will duplicate several times if there are multiline texts.
![SS](https://user-images.githubusercontent.com/22437401/60393154-4be62980-9b43-11e9-9cbe-d1243c0f2ffd.PNG)

**Comment by tianyu-meng** [comment]
Duplicated texts are emitted by upstream TextractorCLI.

This can be fixed by one of the following ways:
- Fix Textractor to emit correct texts.
- Dedupe the texts recursively, using regex may be simplest way.

**Comment by rxia24** [comment]
I found a very bad way to due with is case , scence It's duplicate by whole phrases. XD
See it in my PR https://github.com/rxia24/YUKI/pull/1/files
