### ISSUE TITLE
钩子获取文字重复

### ISSUE THREAD

**Issue by AC12138** [project-yuki/YUKI#111]
如图
![image](https://user-images.githubusercontent.com/45938397/80165245-a9d18980-860d-11ea-949e-c6f32f25e03b.png)

**Comment by tinyAdapter** [comment]
https://github.com/project-yuki/YUKI/blob/master/docs/FAQ_CN.md#%E5%A6%82%E4%BD%95%E5%8E%BB%E9%99%A4%E6%96%87%E6%9C%AC%E4%B8%AD%E5%87%BA%E7%8E%B0%E7%9A%84%E5%8F%A0%E5%AD%97%E5%A6%82%E5%8F%98-aaabbbccc-%E4%B8%BA-abc

**Comment by AC12138** [comment]
谢谢！
