### ISSUE TITLE
Translation texts missing if TaskNo more than 15

### ISSUE THREAD

**Issue by rxia24** [project-yuki/YUKI#16]
Often happened when it translates more than 15 or 16 or 17 times, then the translation texts will missed.
It only happened in version 0.7.

![捕获](https://user-images.githubusercontent.com/22437401/65162118-5e4d7080-da6b-11e9-9e3d-6f739b8d4a04.PNG)

Seems caused by the 'delete' command didn't work well in src/translator/store/modules/Hooks.ts 

``` javascript
   if (texts[texts.length - MAX_STORE_COUNT - 1]) {
      delete texts[handleString][texts.length - MAX_STORE_COUNT - 1]
      delete state.translations[handleString][texts.length - MAX_STORE_COUNT - 1]
    }	    }
```

**Comment by tinyAdapter** [comment]
I've reproduced this bug. It's simply because of the double dereference of texts:
```ts
    const texts = state.texts[handleString]/*THIS ONE*/
    if (texts[texts.length - MAX_STORE_COUNT - 1]) {
      delete texts[handleString]/*WHY AGAIN!?*/[texts.length - MAX_STORE_COUNT - 1]
      delete state.translations[handleString]/*WHY AGAIN!?*/[texts.length - MAX_STORE_COUNT - 1]
    }
```

However, I always use MeCab to generate patterns, so this cannot be discovered.

(By the way, 'delete' command itself seems okay in this case, although it breaks the JS array in theory)

**Comment by rxia24** [comment]
Thanks for you clearly answer!😃
