### ISSUE TITLE
文字祸之子hook文本错乱

### ISSUE THREAD

**Issue by Isayama-Kagura** [project-yuki/YUKI#160]
![PLJX29D(WU`2R8A14(C~J`5](https://user-images.githubusercontent.com/30114848/120884327-25757680-c615-11eb-8df4-873a8bde9745.png)
第一眼看上去是一个句子重复出现了两次，但是前面的句子又少了几个假名

**Comment by luojunyuan** [comment]
/HV-4@EB290:mojika.exe

**Comment by Isayama-Kagura** [comment]
> /HV-4@EB290:mojika.exe

这个文本能显示全了，但是会变成重复了一次
![image](https://user-images.githubusercontent.com/30114848/122403002-92dbbc80-cfb0-11eb-9d55-e82181fce59b.png)

**Comment by Isayama-Kagura** [comment]
> /HV-4@EB290:mojika.exe

不过也算能用，感谢大佬提供的特殊码
