### ISSUE TITLE
Translation missing and Mecab issue.

### ISSUE THREAD

**Issue by rxia24** [project-yuki/YUKI#19]
Similar case with #16 , translation missing if payload.id more than 23

Console log
```
Hooks.ts?5543:129 Uncaught TypeError: Cannot read property '23' of undefined
    at Store.MERGE_TRANSLATION (Hooks.ts?5543:129)
    at wrappedMutationHandler (F:\YUKI-master\node_…\vuex.common.js:727)
    at commitIterator (F:\YUKI-master\node_…\vuex.common.js:393)
    at Array.forEach (<anonymous>)
    at F:\YUKI-master\node_…\vuex.common.js:392
    at Store._withCommit (F:\YUKI-master\node_…\vuex.common.js:523)
    at Store.commit (F:\YUKI-master\node_…\vuex.common.js:391)
    at Store.boundCommit [as commit] (F:\YUKI-master\node_…\vuex.common.js:336)
    at local.commit (F:\YUKI-master\node_…\vuex.common.js:681)
    at Store.mergeTranslation (Hooks.ts?5543:205)
```
Source
```
  MERGE_TRANSLATION (
    state: yuki.TranslatorHookState,
    payload: yuki.TranslationMessage
  ) {
    if (!state.translations[payload.id.toString()]) {
      state.translations[payload.id.toString()] = []
    }
    state.translations[state.currentDisplayHookIndex] = {  //<--- Line 129
      ...state.translations[state.currentDisplayHookIndex],
      [payload.id.toString()]: {
        ...state.translations[state.currentDisplayHookIndex][payload.id.toString()],
        ...payload.translation
      }
    }
  }

```

I'm very new with Js/Ts can't found the reason.

Another side issue, I have installed Mecab, 
but it can't work with release version, the wired thing is that Mecab is functional under "npm run dev".

**Comment by tinyAdapter** [comment]
For the first problem, try to __delete__ line 125-127
```ts
    if (!state.translations[payload.id.toString()]) {
      state.translations[payload.id.toString()] = []
    }
```
and see if the problem still exists. This is legacy code that does not fit current ```state.translations``` structure. I'll fix it in the next release.

For the second problem, I have no idea why this would happen, but MeCab in [the libraries repo](https://github.com/project-yuki/libraries/blob/master/_pack/pos.mecab-ipadic.zip) has been tested by me and works well. The only problem I guess is that YUKI calls MeCab by libmecab.dll, in other words, a direct DLL call, not by executing mecab.exe and get results from console output, so maybe there will be some bugs due to OS compatibility.

**Comment by rxia24** [comment]
For the first issue, tried with the solution but problem still exists at my side.😂

For the second issue, the MeCab which provided by you works well, many Thx.

**Comment by tinyAdapter** [comment]
Hmmm weird. I didn't get any issues testing all of games I own (eight games). On which game did you encounter this problem? Maybe I must get that one to do further checking...

**Comment by rxia24** [comment]
As I tested, Any kinds of game without using Mecab will cause that issue.
Most of my game are base on Krkr engine,
I'm encouter this issue in [ORCSOFT] Teisoukannen ZERO.
try to translate more than 23 sentences.

**Comment by tinyAdapter** [comment]
Okay...Well you should say games are playing without MeCab in advance 😂

Disabling MeCab, I also got this issue now.

After carefully testing, I found that the whole ```state.translations``` object has been cleared after the 23rd translations appeared. Rechecking the code, finally located the culprit at line 92:

```ts
    const texts = state.texts[handleString]
    if (texts[texts.length - MAX_STORE_COUNT - 1]) {
      delete texts[texts.length - MAX_STORE_COUNT - 1]
      delete state.translations/*SXXT WHY DO NOT DEREFERENCE THIS TIME*/[texts.length - MAX_STORE_COUNT - 1]
    }
```

Yes, the main reason is that this time I didn't dereference the ```state.translation``` object, thus deleting the upper level object...

Adding dereference, the code becomes:
```ts
    const texts = state.texts[handleString]
    if (texts[texts.length - MAX_STORE_COUNT - 1]) {
      delete texts[texts.length - MAX_STORE_COUNT - 1]
      delete state.translations[handleString][texts.length - MAX_STORE_COUNT - 1]
    }
```

This time things should be done well.

But there still remains a question: Why the magic number "23"?

Under the false non-dereference logic, the object can be deleted if a translating hook has handle id 6. So, maybe Krkr engine always returns a valid hook with id 6? I have no idea...

That's all I tried. You may add dereference yourself and notify me whether the issue has been fixed.

**Comment by rxia24** [comment]
After adding dereference, it's fixed.

About the hook id, if you mean this value "state.currentDisplayHookIndex",
I've log it out before, it's always 7. Don't know whether related to this issue or not...

Thx for your kind reply and effort.😄
