### ISSUE TITLE
求加入hentai词条

### ISSUE THREAD

**Issue by RyouOo** [project-yuki/YUKI#21]
在论坛发帖推荐YUKI翻译器，坛友反应需要hentai词条
翻了翻应该是这个？
http://www.vnr.cn/a/161.html
求加入此功能

**Comment by tinyAdapter** [comment]
自定义词条是个大坑……目前还没想到什么好的实现方式（VNR的词条系统本身设计极其复杂，很难借鉴），所以暂时应该不会考虑了😶

↑以上当然其实只是说辞，我大可以先试着实现一个简单的版本，后续再完善

然而没时间才是重点233

怎么说呢，相比于一些代码量不多的小功能点，这种大型系统实现起来确实比较费时费力，需要**连续的**开发时间，而我现在又没这种时间

\*你看我[大型系统的计划](https://github.com/project-yuki/planning/issues)都排了多少了，咕了咕了\*

---

这里我可以说一下实现要点，有谁想接坑的话可以照着做：

1. 暂时以单词为模式，不考虑跨词短语（也就无需正则表达式匹配）
2. 重新设计一个通用的，可以向后兼容的配置文件格式（VNR的词条数据可以放弃了，太难迁移）
3. 架构需要更改，把自定义词条系统加到Renderer IPC 请求翻译->Main IPC 传回翻译结果之间

就这些吧……

**Comment by RyouOo** [comment]
谢谢回复，加油！


来自 魅族 16th

-------- 原始邮件 --------
发件人：tinyAdapter <notifications@github.com>
时间：2019年10月13日 01:20
收件人：project-yuki/YUKI <YUKI@noreply.github.com>
抄送：RyouOo <ryouooizumi@163.com>,Author <author@noreply.github.com>
主题：Re: [project-yuki/YUKI] 求加入hentai词条 (#21)
