### ISSUE TITLE
不能启用本地j北京

### ISSUE THREAD

**Issue by 123456ds** [project-yuki/YUKI#28]
不能启用本地j北京（无法选择路径）

<a href="https://sm.ms/image/gdxfPj5veEXMOpC" target="_blank"><img src="https://i.loli.net/2019/11/09/gdxfPj5veEXMOpC.png" ></a>

**Comment by tinyAdapter** [comment]
这个不是用来指定J北京本体的路径，而是指定J北京自定义词典的路径，并且目前这个功能处于不必要的状态（因为自定义词典已经被打包到了程序中，只需要指定路径即可），只是暂时用来测试下载模块功能的，后续会改掉。

如果想要指定J北京翻译的话，暂时需要手动修改config\config.json配置文件里的translators.jBeijing对象：

```json
"translators": {
    "jBeijing": {
      "dictPath": "<你的YUKI文件夹绝对路径，每个反斜杠后再多加一个，像右边那样>\\lib\\dict\\jb",
      "enable": true,
      "path": "<你的J北京文件夹绝对路径，每个反斜杠后再多加一个>"
    }
  }
```

重启YUKI即可。
