### ISSUE TITLE
无法启动游戏

### ISSUE THREAD

**Issue by 123456ds** [project-yuki/YUKI#29]
LE执行方式是，"E:LE\LEProc.exe" -run %GAME_PATH%

<a href="https://sm.ms/image/QqCYITvW3wmN9A8" target="_blank"><img src="https://i.loli.net/2019/11/09/QqCYITvW3wmN9A8.png" ></a>

**Comment by tinyAdapter** [comment]
如果执行方式没复制错的话，缺了一个反斜杠

```
"E:\LE\LEProc.exe" -run %GAME_PATH%
```

而不是

```
"E:LE\LEProc.exe" -run %GAME_PATH%
```

**Comment by 123456ds** [comment]
可以使用了，是区域设置没有保存的结果。

<a href="https://sm.ms/image/RKLhMunXSQUksdz" target="_blank"><img src="https://i.loli.net/2019/11/09/RKLhMunXSQUksdz.png" ></a>
问下翻译窗口怎么设置为透明（只显示原文与翻译结果）

文本提取有点小问题，姓名被置后后。

**Comment by tinyAdapter** [comment]
翻译窗口没有办法透明，为了兼顾操作和Electron自身的一些限制，目前只能实现成这个样子。你可以在翻译器设置里把窗口背景色设置成白色。

文本提取的问题，你可以换换提取钩子，找一个最好的结果，这个跟VNR是一样的。

**Comment by 123456ds** [comment]
感谢。

是这个游戏的问题，看了看其他钩子与vnr的文本设定也是一样的是姓名置后。

发现一个游戏无法同步，おさこい ～俺と二人の甘々ご奉仕H生活～，启动后没有显示翻译窗口，等待一会后软件会自动弹出主页面

**Comment by tinyAdapter** [comment]
等一段时间回到主页面是因为游戏无法正常被文本提取器注入，重试10次失败后退出，具体原因千奇百怪，没什么统一的解决方案。

如果游戏本身运行正常的话，可以直接用[Textractor](https://github.com/Artikash/Textractor)试试看能不能正常注入，毕竟YUKI是用的Textractor作为文本提取核心。
