### ISSUE TITLE
老哥你的YUKI近期反馈评价较多是由我引起的，在此我说明一下。

### ISSUE THREAD

**Issue by shanghaisanta** [project-yuki/YUKI#31]
抱歉哈，我只是一个大学生路人，偶然玩一个车万同人(终于遇到同党了！）galgame，由pre-blossom 同人社团出品的"Scarlet [Alchemy",跟随一篇论坛帖子找到的这个软件，试用了一下感觉还不错就在百度贴吧，galgame吧发帖宣传了一下，我没有在发帖前提前通知作者你，在此道歉，突然给你带来的许多反馈惊扰还请见谅。如果可以的话，能否进入百度贴吧>galgame吧>搜索帖子>推荐一个国人自研翻译软件,里面有许多用户反馈的问题，他们大多不会用github反馈，都写在帖子里了，请作者大大看一下利于改进软件。我也没想到一发帖这么多回复，给你带来的压力再次道歉，谢谢作者大大！加油！底下附上帖子地址。
https://tieba.baidu.com/p/6331257658?pid=128241287695&cid=0&red_tag=0090673195#128241287695

**Comment by tinyAdapter** [comment]
好的，我知道了😂
