### ISSUE TITLE
win10打不开游戏

### ISSUE THREAD

**Issue by 332879969** [project-yuki/YUKI#32]
您好，我下载的最新版本，设置好le，添加好游戏之后，点击开始之后软件跳到最小化过几秒之后又原样跳出来，并启动不了游戏，试验了2款游戏都打不开，求问是什么原因，谢谢

**Comment by 332879969** [comment]
补充一下，在win8上也实验了一下也是同样的结果，即使把设置都初始化了之后也是点开始游戏之后启动不了 ，也什么都不提示

**Comment by tinyAdapter** [comment]
启动游戏或者文本提取器注入DLL失败会导致这个结果，详见 https://github.com/project-yuki/YUKI/issues/29#issuecomment-552072371

**Comment by 332879969** [comment]
谢谢，但是最主要什么都没有报错，我想问下软件有没有日志文件，我想看看错误的信息

**Comment by tinyAdapter** [comment]
以前曾经有日志文件生成的，但是后来用起来感觉太麻烦就去掉了，现在可以在命令行里输

```
set DEBUG=yuki:* && set DEBUG_COLORS=1 && YUKI.exe
```

启动YUKI并得到实时debug信息

**Comment by 332879969** [comment]
好的，我试试看
