### ISSUE TITLE
关于钩子转区钩不上的问题

### ISSUE THREAD

**Issue by MasouShizuka** [project-yuki/YUKI#34]
如果区域转换器设置为localeEmulator，点击运行打开游戏后，文本钩子上显示Textractor:couldn'tinject。
如果区域转换器设置为noChanger，即直接打开，点击运行打开游戏后，能正常获取文本。

举例：对于某个可转区打开也可直接打开的游戏，localeEmulator打开文本钩子上显示Textractor:couldn'tinject，noChanger打开可正常获取文本并正常翻译。

其他建议：能否增加直接将翻译窗口依附在已打开程序上的功能，即相当于自己（转区）打开游戏，再用YUKI寻找某已打开exe进程并将窗口依附在上面。

**Comment by tinyAdapter** [comment]
什么游戏会遇到这种情况？我目前还没遇到过……可以换ntleas或者别的转区软件试试看。

另外关于注入已打开程序的功能，实现倒是可以实现，但一方面这样丧失了YUKI作为启动器的功能，使得每次都要手动开游戏+找进程PID；另一方面其实和从YUKI开程序再注入本质上来说应该是没有区别的，因为YUKI也不过是打开程序->调用Textractor注入->接收结果并做后续处理，自己开只是省去了打开程序的步骤，后面两步还是必须要完成的。

我看看什么时候实现一下吧，应该优先级不是太高。

**Comment by MasouShizuka** [comment]
已解决
第一次用LE打开某一游戏时，勾选了用管理员权限运行会导致钩子不能注入
取消用管理员权限运行即可（即默认设置打开）

建议：可以考虑添加一个针对某一游戏编写正则表达式过滤文本的功能，这样可以过滤掉某些游戏特有的垃圾文本

**Comment by MasouShizuka** [comment]
对了，至于我说的增加直接将翻译窗口依附在已打开程序上的功能，是因为有时候运行，游戏打开了，但YUKI并不能依附在窗口上。
当然，这个问题只要重开YUKI基本上就能解决，所以此功能并不是特别重要。

最后：感谢您的回复，祝您一路顺风。
