### ISSUE TITLE
重复句子与词汇

### ISSUE THREAD

**Issue by 123456ds** [project-yuki/YUKI#38]
重复句子与词汇

<a href="https://sm.ms/image/ICW4vq6ygHp7Be1" target="_blank"><img src="https://i.loli.net/2019/11/20/ICW4vq6ygHp7Be1.png" /></a>

<a href="https://sm.ms/image/3ael4qhGKITgL56" target="_blank"><img src="https://i.loli.net/2019/11/20/3ael4qhGKITgL56.png" /></a>

<a href="https://sm.ms/image/PCSiMp2eTFHa75z" target="_blank"><img src="https://i.loli.net/2019/11/20/PCSiMp2eTFHa75z.png" /></a>

**Comment by luojunyuan** [comment]
编辑 `YUKI/config/text.json` 
将 `deduplicate` 项设置为 `true`
可能需要重启YUKI
[参考](https://github.com/project-yuki/YUKI/blob/master/docs/ConfigFiles_CN.md#%E9%BB%98%E8%AE%A4%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6-2)
