### ISSUE TITLE
[feature]建议添加自动化编译

### ISSUE THREAD

**Issue by liududu** [project-yuki/YUKI#4]
搞了半天部署不上😂，而且感觉另外搞C++开发环境太麻烦了。我觉得这个项目很有前途，可以考虑添加自动化编译。这样也能及时跟上新功能

**Comment by tinyAdapter** [comment]
CI那一套么？之前我看了一下感觉有点麻烦，而且最初项目写得比较tricky，很难被自动化，所以就暂时搁置了。不过现在感觉node这一套流程基本摸清之后应该是可以上自动化了。我试试看吧，不行再说😂

**Comment by tinyAdapter** [comment]
搞定了，不过以后主分支只能用来发布了 emmm
