### ISSUE TITLE
需要用AlphaROMdiE破解的游戏如何打开？

### ISSUE THREAD

**Issue by gitwwj** [project-yuki/YUKI#40]
![Snipaste_2019-11-20_17-29-01](https://user-images.githubusercontent.com/57986394/69226719-908a6400-0bbb-11ea-806b-1b0d0c0d1005.png)

AlphaROMdiE是打开后将游戏程序拖拽到上面，yuki里该怎么设置打开这类游戏？
或者说，我不通过yuki先打开游戏，然后怎么用钩子钩取文本？

**Comment by PpiLiu** [comment]
![image](https://user-images.githubusercontent.com/44269904/69314941-62b32700-0c70-11ea-8fa8-9bc65068d452.png)
AlphaROMdiE也可以通过设置为区域转换器，之后只要把对应游戏的启动方式设置为AlphaROMdiE就可以直接在YUKI内启动了
![image](https://user-images.githubusercontent.com/44269904/69315075-af96fd80-0c70-11ea-9ee4-c34e019fa1bf.png)

**Comment by gitwwj** [comment]
> ![image](https://user-images.githubusercontent.com/44269904/69314941-62b32700-0c70-11ea-8fa8-9bc65068d452.png)
> AlphaROMdiE也可以通过设置为区域转换器，之后只要把对应游戏的启动方式设置为AlphaROMdiE就可以直接在YUKI内启动了
> ![image](https://user-images.githubusercontent.com/44269904/69315075-af96fd80-0c70-11ea-9ee4-c34e019fa1bf.png)

十分感谢！

**Comment by luojunyuan** [comment]
使用 Build20121001 版本也可以直接产生crake版本的exe程式
