### ISSUE TITLE
麻烦下作者大大问下转区无法生效怎么办?

### ISSUE THREAD

**Issue by lingdongyishi** [project-yuki/YUKI#45]
![QQ图片20191126052122](https://user-images.githubusercontent.com/57443459/69579332-3f400180-100d-11ea-9362-b47aa6fdd4a4.png)
![QQ图片20191126052140](https://user-images.githubusercontent.com/57443459/69579343-4404b580-100d-11ea-8c39-10df6ed3c5e6.png)
设置的有哪里不对么,改了好多次都是不管用的,win10系统

**Comment by tinyAdapter** [comment]
有多种情况：
1. 执行方式写的不对，检查一下LEProc.exe是不是真的在这个路径
2. LE版本太低，如果你是Win10 1903以上的系统版本，那么至少要把LE升到[v2.4.0.0以上](https://github.com/xupefei/Locale-Emulator/releases)
3. LE没办法工作的游戏，换别的区域转换器试试

**Comment by lingdongyishi** [comment]
> 
> 
> 有多种情况：
> 
>     1. 执行方式写的不对，检查一下LEProc.exe是不是真的在这个路径
> 
>     2. LE版本太低，如果你是Win10 1903以上的系统版本，那么至少要把LE升到[v2.4.0.0以上](https://github.com/xupefei/Locale-Emulator/releases)
> 
>     3. LE没办法工作的游戏，换别的区域转换器试试

1路径肯定没错,就在这里.
2我的版本号是2.4.1.0
3我单独用LE打开过程序能够转区没有问题.

**Comment by tinyAdapter** [comment]
这还真的是有够怪的……调试信息页面能截一下么？

**Comment by lingdongyishi** [comment]
![QQ图片20191126134414](https://user-images.githubusercontent.com/57443459/69602699-720ce880-1053-11ea-9520-9efbc8a4e7d7.png)
![QQ图片20191126134806](https://user-images.githubusercontent.com/57443459/69602702-7507d900-1053-11ea-9d50-11b96f86b1ac.png)
![QQ图片20191126134811](https://user-images.githubusercontent.com/57443459/69602705-776a3300-1053-11ea-8239-d36d45cd6a42.png)
我又换了一个游戏打开,结果不是不能转区是错误了

**Comment by lingdongyishi** [comment]
![QQ图片20191126135056](https://user-images.githubusercontent.com/57443459/69602886-f495a800-1053-11ea-86da-974d56cb9fdf.png)
这是调试信息,我试着删除原来添加的游戏再打开也错误了

**Comment by lingdongyishi** [comment]
单独用LE打开都没有问题

**Comment by tinyAdapter** [comment]
会不会是这个游戏启动了之后创建了一个新的不叫nime.exe的进程然后就退出了啊……？

你看一下任务管理器->详细信息里这个游戏进程到底叫什么，如果不叫nime.exe的话，YUKI暂时没办法对这种情况工作（因为没办法正常从进程名获取进程PID）

**Comment by lingdongyishi** [comment]
![QQ图片20191126141734](https://user-images.githubusercontent.com/57443459/69604132-8a7f0200-1057-11ea-98c3-816186da7003.png)
就叫这个

**Comment by tinyAdapter** [comment]
好奇怪啊……我没办法解决了 :(

下一版应该会加入从正在运行的游戏进程启动翻译器，到时候你可以先手动用LE开游戏再用那个启动翻译

**Comment by lingdongyishi** [comment]
好吧...没法子了,那就这样吧

**Comment by tinyAdapter** [comment]
等一下……你是不是把运行方式写成了

"D:\Locale Emulator\LEProc.exe"（回车）
%GAME_PATH%

了啊……

**Comment by tinyAdapter** [comment]
这样的话后面的游戏路径就会被命令行截断，改成

"D:\Locale Emulator\LEProc.exe" （空格）%GAME_PATH%

应该就好了

**Comment by lingdongyishi** [comment]
![QQ图片20191126144734](https://user-images.githubusercontent.com/57443459/69605672-b8fedc00-105b-11ea-8e29-7ab68e6dbdd5.png)
![QQ图片20191126144740](https://user-images.githubusercontent.com/57443459/69605675-bb613600-105b-11ea-8e85-5a64506f5cef.png)
![QQ图片20191126144744](https://user-images.githubusercontent.com/57443459/69605681-bdc39000-105b-11ea-8fbd-685c9084baa0.png)
跟空格还是回车没有关系..我都试过..

**Comment by tinyAdapter** [comment]
╮(╯-╰)╭

**Comment by luojunyuan** [comment]
这个游戏不转区启动文本会乱码吗？

请尝试No Changer 不转区启动试试

**Comment by asukaminato0721** [comment]
可以曲线救国，先转区打开 exe，然后 yuki 从进程启动
