### ISSUE TITLE
Textrator：architecture mismatch ：only Tetractor x64 caninject this processnull

### ISSUE THREAD

**Issue by xiandaD** [project-yuki/YUKI#48]
体系结构不匹配：只有textractor x64可以进入此进程。
我一挂钩子就会出现这个提示，四个翻译器都是。请问是什么问题？

**Comment by tinyAdapter** [comment]
游戏是64位的，必须使用64位的Textractor才能正常注入，请从[这里](https://github.com/Artikash/Textractor/releases)下载Zip-Version压缩包，把x64版本的TextractorCLI.exe和texthook.dll替换 lib\textractor 目录下的同名文件

因为一般Gal都是32位的，所以我没把64位的Textractor打包进YUKI里

要换32位的游戏的话，不要忘记换回x86的Textractor
