### ISSUE TITLE
反馈一下竹子社的游戏YUKI都打不开，请作者修复一下。

### ISSUE THREAD

**Issue by shanghaisanta** [project-yuki/YUKI#49]

**Comment by luojunyuan** [comment]
我上个月的JK妹都没啥问题，你啥都不说反馈个锤子

**Comment by rxia24** [comment]
![捕获](https://user-images.githubusercontent.com/22437401/70368132-3b9c5c80-18e2-11ea-88dc-b4df4b751493.PNG)

出现问题请先检查自己的配置，仔细阅读[ConfigFiles_CN.md](https://github.com/project-yuki/YUKI/blob/master/docs/ConfigFiles_CN.md)

还有请将问题请描述清楚，最好带上截图或者错误信息，有助于别人帮助解决。
你这样丢一句话就走真的非常让人摸不着头脑，你应该知道这里不是售后服务中心。
