### ISSUE TITLE
只能翻译弹窗文字

### ISSUE THREAD

**Issue by hecheng1996lzg** [project-yuki/YUKI#50]
老哥求解，我玩的游戏是“ToHeart2 XRATED”，能够正常打开，跨区等都没问题，但是进入后的文字钩子选项列表中只要游戏窗口名称， 游戏弹窗等日文能正常翻译，但是就是找不到游戏内对话的日文。希望老哥有空的时候能帮忙解答下，感谢了。

**Comment by tinyAdapter** [comment]
不能自动提取的游戏需要特殊码，你可以去VNR吧找找看

**Comment by hecheng1996lzg** [comment]
好的了解了。感谢。我找找

**Comment by luojunyuan** [comment]
/HS-4@4B4A50
找了一个整页的码
意义不大啊、
1.02

**Comment by hecheng1996lzg** [comment]
QAQ 感谢，帮大忙了。
我自己去尝试找了下，没找到。
请问下是在搜到的，下次我还可以找找别的，哈哈哈。
