### ISSUE TITLE
关于词典解释条目高度过低的问题

### ISSUE THREAD

**Issue by MasouShizuka** [project-yuki/YUKI#52]
问题：点击翻译窗口的原文出现的词典解释条目的高度限制在翻译窗口内，若翻译窗口高度过低，则条目的高度会被限制，只能通过滚轮一行一行看
![01](https://user-images.githubusercontent.com/44764707/70387844-117f9300-19e5-11ea-99fb-a86223d03306.png)

顺便建议：VNR中Mecab可以选择将原文的罗马音全部显示在原文上，能否实现此功能

**Comment by tinyAdapter** [comment]
想了一下，可以点击的时候把窗口高度增大，关闭后再还原。当初实现的时候没想到这一点……

关于另外一点，我不知道全部显示有什么用，不过实现是可以实现的，也没啥工作量，顺带搞一下好了 :)

**Comment by MasouShizuka** [comment]
有一部分人是二次元作品看得多，导致能听得懂，但是看不懂。所以通过罗马音可以知道怎么读，就能理解意思（没错，就比如我这种人- -！）。
这样就可以边玩边记日文，相当于学习日语五十音图一样。
