### ISSUE TITLE
vnr的人工字幕是怎么实现的？

### ISSUE THREAD

**Issue by luojunyuan** [project-yuki/YUKI#54]
好弄吗，给yuki添加这项功能怎么样呀？
很想把vnr的(樱之诗)人工字幕们都给导入进来。

ps.建议文本去重的逻辑最好针对每一张游戏card，理想的样子是优先原生提取到的文本。选择性的对游戏开启文本去重（╹◡╹）

**Comment by tinyAdapter** [comment]
应该是和自定义辞典一样用服务器存吧，具体我没看VNR代码

感觉这种需要在线同步的东西都太遥远了……

**Comment by luojunyuan** [comment]
> 应该是和自定义辞典一样用服务器存吧，具体我没看VNR代码
> 
> 感觉这种需要在线同步的东西都太遥远了……

好吧。。只能馒馒来了😭、
