### ISSUE TITLE
能否增加去除叠字的功能

### ISSUE THREAD

**Issue by Amano-Aki** [project-yuki/YUKI#58]
如题，在一些游戏中，提取出的文本会出现叠字，例如「おお客客ささんん」这样，非常影响分词和翻译的效果。求问可否增加去除叠字的功能？

**Comment by tinyAdapter** [comment]
https://github.com/project-yuki/YUKI/blob/master/docs/ConfigFiles_CN.md#textsjson

修改config\text.json，设置modifier.deduplicate为true，重启YUKI即可
