### ISSUE TITLE
使用有道翻译经常出现{}然后就一直没有翻译了

### ISSUE THREAD

**Issue by GasaiMaple** [project-yuki/YUKI#61]

**Comment by luojunyuan** [comment]
这应该是因为有道QPS限制，或者是有道给同一ip限制了翻译使用量的原因。不信可以切一个wifi试试立马就能用了。可以 `config/config.json` 中有道关掉
```json
    {
      "enable": true,
      "external": true,
      "jsFile": "config\\hjdictApi.js",
      "name": "有道"
    },
```

**Comment by GasaiMaple** [comment]
> 这应该是因为有道QPS限制，或者是有道给同一ip限制了翻译使用量的原因。不信可以切一个wifi试试立马就能用了。可以 `config/config.json` 中有道关掉
> 
> ```json
>     {
>       "enable": false,
>       "external": true,
>       "jsFile": "config\\hjdictApi.js",
>       "name": "有道"
>     },
> ```

但是每次重启游戏就会重新恢复，如果没重启等多久都一样

**Comment by tinyAdapter** [comment]
我发现了个bug……为啥有道给的jsFile是沪江的😂

**Comment by tinyAdapter** [comment]
> > 这应该是因为有道QPS限制，或者是有道给同一ip限制了翻译使用量的原因。不信可以切一个wifi试试立马就能用了。可以 `config/config.json` 中有道关掉
> > ```json
> >     {
> >       "enable": false,
> >       "external": true,
> >       "jsFile": "config\\hjdictApi.js",
> >       "name": "有道"
> >     },
> > ```
> 
> 但是每次重启游戏就会重新恢复，如果没重启等多久都一样

沪江估计最近加了单个session的访问限制，以前是没有的，所以我没加刷新session的代码（像有道API那样的），加上应该就好了

**Comment by luojunyuan** [comment]
> 我发现了个bug……为啥有道给的jsFile是沪江的😂

真的绝了！用了几个月才发现😂，照你说的改好了~

**Comment by luojunyuan** [comment]
> 这应该是因为有道QPS限制，或者是有道给同一ip限制了翻译使用量的原因。不信可以切一个wifi试试立马就能用了。可以 `config/config.json` 中有道关掉
> 
> ```json
>     {
>       "enable": false,
>       "external": true,
>       "jsFile": "config\\hjdictApi.js",
>       "name": "有道"
>     },
> ```

@GasaiMaple 你先把`jsFile`改成`youdaoApi.js`就能用有道啦
```
    {
      "enable": true,
      "external": true,
      "jsFile": "config\\youdaoApi.js",
      "name": "有道"
    },
```
