### ISSUE TITLE
剪贴板文字不更新

### ISSUE THREAD

**Issue by dewrfe53535** [project-yuki/YUKI#64]
在剪贴板改变之后，yuki中的clipboard没有发生改变

**Comment by tinyAdapter** [comment]
测试了一下，CLI版本的Textractor只会在开启程序时抓取一次剪贴板的内容，GUI版会持续抓取，可能是一个BUG，如果你确实需要从剪贴板获取文本的话，可以去 https://github.com/Artikash/Textractor/issues 提issue

不过为何需要这项功能呢？因为Textractor既是目前自动获取文本钩子的最好方案，又可以像VNR一样输入特殊码，按理来说不会再需要从什么别的程序折腾剪贴板了……

**Comment by dewrfe53535** [comment]
> 测试了一下，CLI版本的Textractor只会在开启程序时抓取一次剪贴板的内容，GUI版会持续抓取，可能是一个BUG，如果你确实需要从剪贴板获取文本的话，可以去 https://github.com/Artikash/Textractor/issues 提issue
> 
> 不过为何需要这项功能呢？因为Textractor既是目前自动获取文本钩子的最好方案，又可以像VNR一样输入特殊码，按理来说不会再需要从什么别的程序折腾剪贴板了……

スタディ§ステディ v1.02版找了一圈没找到现成的特殊码，看网上的特殊码教程搞了半天搞不出来，但cheat engine可以搜到一个读取存档后不会改变的文本地址，通过lua脚本可以实现自动复制

英语不行，用机翻去那边提人家大概看不懂......但不是这边的问题的话那就close了

**Comment by luojunyuan** [comment]
我在[vndb](https://vndb.org/t12933)上找到一个hcode，不知是否能用
`/HW4@16F5EE:ststeady.exe`

**Comment by dewrfe53535** [comment]
> 我在[vndb](https://vndb.org/t12933)上找到一个hcode，不知是否能用
> `/HW4@16F5EE:ststeady.exe`

不能，这个是原版补丁，不适用于19/12/27更新后的v1.02

**Comment by luojunyuan** [comment]
这是1.02的对应之前的1.01的码的偏移 `/HW4@1701DE:ststeady.exe`

![image](https://user-images.githubusercontent.com/28323948/72632082-7c32cf80-3990-11ea-9850-1fdce005f3a0.png)
不知道是不是我换了电脑运行库没装全的原因，yuki与textractor都不能注入这个游戏。
不能帮你测试了，从调试器中的情况来看应该是正确的

**Comment by dewrfe53535** [comment]
可以了！感谢 ！

k1mlka <notifications@github.com> 于2020年1月18日周六 上午1:23写道：
