### ISSUE TITLE
正常词语被去叠字过滤

### ISSUE THREAD

**Issue by rxia24** [project-yuki/YUKI#65]
新年快乐，身体健康！

已确定config\text.json 中 modifier.deduplicate为 false，正常词语也被识别成叠字了。

如图所示：
![image](https://user-images.githubusercontent.com/22437401/73122458-2083ca00-3fc0-11ea-8105-8a1c0645e905.png)

**Comment by tinyAdapter** [comment]
不应该啊……试过别的游戏了么？我这边测试是没问题的

有一个想法：可能是提取到的原始文本就被去掉了叠字……看看别的钩子？

**Comment by rxia24** [comment]
搞清楚了，是这个游戏社团的游戏都会这样，
和你猜想的一致，有的钩子提取到的原始文本就去掉了叠字，有的原始文本就把每个文字重复一遍。

![image](https://user-images.githubusercontent.com/22437401/73130202-d128b280-402e-11ea-9e5a-ba88f549f11f.png)

不过我把 modifier.deduplicate 改为true, 会把正常的字识别为叠字，或许有办法让它之过滤一次？
![image](https://user-images.githubusercontent.com/22437401/73130176-48117b80-402e-11ea-845a-6921af2613b4.png)

**Comment by CPCer** [comment]
@rxia24 可能还是游戏的问题？或者作者已经更新？我这边开了去叠字，不会把正常的重复去了……
不过我偶尔遇到整句重复，没去掉

**Comment by CPCer** [comment]
噫，发现我的去叠字也会去正常的字，，打脸太突然……
