### ISSUE TITLE
游戏运行没有YUKI窗口显示

### ISSUE THREAD

**Issue by IndexBox** [project-yuki/YUKI#69]

**Comment by tinyAdapter** [comment]
调试信息的内容是啥？

**Comment by IndexBox** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tinyAdapter"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月11日(星期二) 中午1:59
收件人:&nbsp;"project-yuki/YUKI"<YUKI@noreply.github.com&gt;;
抄送:&nbsp;"流云若雪"<1175480887@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [project-yuki/YUKI] 游戏运行没有YUKI窗口显示 (#69)




调试信息的内容是啥？

**Comment by IndexBox** [comment]
应该是这个 但mecab disabled

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tinyAdapter"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月11日(星期二) 中午1:59
收件人:&nbsp;"project-yuki/YUKI"<YUKI@noreply.github.com&gt;;
抄送:&nbsp;"流云若雪"<1175480887@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [project-yuki/YUKI] 游戏运行没有YUKI窗口显示 (#69)

**Comment by IndexBox** [comment]
希望这个软件越做越好，相比其他的翻译软件这个感觉更适合学习者使用

**Comment by tinyAdapter** [comment]
没看见图片，你用命令提示符（cmd）运行YUKI.exe，把文本复制下来发过来吧

**Comment by IndexBox** [comment]
&nbsp; yuki:app __dirname: E:\syx璧勬枡\娓告垙\YUKI\resources\app.asar\dist\electron +0ms
&nbsp; yuki:app basePath: E:\syx璧勬枡\娓告垙\YUKI +3ms
&nbsp; yuki:app appPath: E:\syx璧勬枡\娓告垙\YUKI\resources\app.asar +3ms
&nbsp; yuki:app mainWinURL: file://E:\syx璧勬枡\娓告垙\YUKI\resources\app.asar\dist\electron/index.html +0ms
&nbsp; yuki:config E:\syx璧勬枡\娓告垙\YUKI\config\config.json saved +0ms
&nbsp; yuki:config E:\syx璧勬枡\娓告垙\YUKI\config\config.json loaded with pre-save +8ms
&nbsp; yuki:config E:\syx璧勬枡\娓告垙\YUKI\config\games.json saved +22ms
&nbsp; yuki:config E:\syx璧勬枡\娓告垙\YUKI\config\games.json loaded with pre-save +1ms
&nbsp; yuki:config E:\syx璧勬枡\娓告垙\YUKI\config\texts.json saved +6ms
&nbsp; yuki:config E:\syx璧勬枡\娓告垙\YUKI\config\texts.json loaded with pre-save +1ms
&nbsp; yuki:config E:\syx璧勬枡\娓告垙\YUKI\config\gui.json saved +5ms
&nbsp; yuki:config E:\syx璧勬枡\娓告垙\YUKI\config\gui.json loaded with pre-save +1ms
&nbsp; yuki:downloader:factory library base repo -&gt; https://github.com/project-yuki/libraries/raw/master/_pack/ +0ms
&nbsp; yuki:downloader:factory library base store path -&gt; E:\syx璧勬枡\娓告垙\YUKI\lib +0ms
&nbsp; yuki:app creating window... +186ms
&nbsp; yuki:ipc request config config +0ms
&nbsp; yuki:ipc request config config +273ms
&nbsp; yuki:ipc request config games +4ms
&nbsp; yuki:ipc main page load finished. starting apis... +1ms
&nbsp; yuki:api external file E:\syx璧勬枡\娓告垙\YUKI\config\baiduApi.js loaded +0ms
&nbsp; yuki:api external file E:\syx璧勬枡\娓告垙\YUKI\config\youdaoApi.js loaded +3ms
&nbsp; yuki:api external file E:\syx璧勬枡\娓告垙\YUKI\config\qqApi.js loaded +6ms
&nbsp; yuki:ipc apis started +16ms
&nbsp; yuki:game choose Locale Emulator as locale changer +0ms
&nbsp; yuki:game exec string: "E:\syx璧勬枡\Locale.Emulator.2.4.1.0\LEProc.exe" "E:\syx璧勬枡\娓告垙\鐢佃鏈虹殑娑堝け涔嬫棩\tvlost.exe" +0ms
&nbsp; yuki:game finding pid of tvlost.exe... +456ms
&nbsp; yuki:game could not find game. retry times... 1 +3s
&nbsp; yuki:game could not find game. retry times... 2 +283ms
&nbsp; yuki:game found game. pids [ 10352 ] +798ms
&nbsp; yuki:hooker trying to access CLI exe at E:\syx璧勬枡\娓告垙\YUKI\lib\textractor\TextractorCLI.exe +0ms
&nbsp; yuki:merger initialized true +0ms
&nbsp; yuki:textInterceptor initialized +0ms
&nbsp; yuki:textInterceptor initialized +0ms
&nbsp; yuki:mecab disabled +0ms
&nbsp; yuki:hooker application builded +35ms
&nbsp; yuki:hooker injecting process 10352... +3ms
error: Error: spawn E:\syx璧勬枡\娓告垙\YUKI\lib\textractor\TextractorCLI.exe ENOENT
(node:3792) UnhandledPromiseRejectionWarning: Error: write EPIPE
&nbsp; &nbsp; at afterWriteDispatched (internal/stream_base_commons.js:78:25)
&nbsp; &nbsp; at writeGeneric (internal/stream_base_commons.js:73:3)
&nbsp; &nbsp; at Socket._writeGeneric (net.js:713:5)
&nbsp; &nbsp; at Socket._write (net.js:725:8)
&nbsp; &nbsp; at doWrite (_stream_writable.js:410:12)
&nbsp; &nbsp; at writeOrBuffer (_stream_writable.js:394:5)
&nbsp; &nbsp; at Socket.Writable.write (_stream_writable.js:294:11)
&nbsp; &nbsp; at Textractor.exec (E:\syx璧勬枡\娓告垙\YUKI\resources\app.asar\node_modules\textractor-wrapper\lib\index.js:120:28)
&nbsp; &nbsp; at Textractor.attach (E:\syx璧勬枡\娓告垙\YUKI\resources\app.asar\node_modules\textractor-wrapper\lib\index.js:77:14)
&nbsp; &nbsp; at Hooker.injectProcess (E:\syx璧勬枡\娓告垙\YUKI\resources\app.asar\dist\electron\main.js:1427:25)
(node:3792) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3792) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
&nbsp; yuki:filter [-1] null +0ms
&nbsp; yuki:game found game. pids [ 10352 ] +1s

**Comment by tinyAdapter** [comment]
OK，看起来是Textractor启动失败了。三种可能：

1. 路径中含有特殊字符（如中文、日文、乱码），试一下把YUKI放在全英文目录下。游戏目录带中日文应该没问题，乱码不好说
2. 检查你的TextractorCLI.exe是不是真的在`E:\syx璧勬枡\娓告垙\YUKI\lib\textractor`这个目录下
3. Textractor没办法注入游戏进程，尝试下载最新版[https://github.com/Artikash/Textractor/releases/download/v4.9.1/Textractor-4.9.1-Zip-Version-English-Only.zip](https://github.com/Artikash/Textractor/releases/download/v4.9.1/Textractor-4.9.1-Zip-Version-English-Only.zip)，替换上面那个目录里的TextractorCLI.exe和texthook.dll，重新运行一遍试试

如果都不能解决，我就没有办法了¯\\\_(ツ)\_/¯

**Comment by IndexBox** [comment]
谢谢
