### ISSUE TITLE
[问题]翻译器呼出

### ISSUE THREAD

**Issue by liududu** [project-yuki/YUKI#7]
游戏中不小心把翻译器点X关掉了，如何再次唤出？
关闭游戏重开比较麻烦。
如有[Feature]快捷键，请添加到帮助中。
或者[Feature]添加开启翻译器的后台开关选项

**Comment by tinyAdapter** [comment]
目前的策略是这样，点X关掉翻译器窗口其实只是将该窗口隐藏，如果之后有任何新的文本被文本提取器hook到（比如游戏内有新的文本出现了，进入了下一段对话等等），翻译器窗口会自动重新出现。

关于这部分的交互逻辑我之前也设想了几种方案，最终敲定上面这种，主要是考虑到有时候需要临时关闭翻译器窗口但又不是真的要关闭翻译器（比如需要临时看一下完整的游戏画面，打开设置菜单进行设置等）。

当然这种策略也不是就多么完美，因为有些游戏当你做出一些游戏内操作（鼠标右键，打开设置菜单等）时会产生一些能被hook到的文本，会导致窗口反复弹出来干扰画面，所以如果有更好的交互方式的话欢迎提出来😉

**Comment by liududu** [comment]
谢谢解答，我觉得交互策略以后可以考虑加入到自定义选项中。
