### ISSUE TITLE
开启自动隐藏标题栏功能后出现窗口抖动问题

### ISSUE THREAD

**Issue by mutouchan** [project-yuki/YUKI#71]
RT，开启后在翻译栏隐藏标题功能实现后，把鼠标指针放在原标题栏位置会导致整个窗口不断抖动，需要鼠标左键长按标题栏才会停止跳动。
同时建议添加VNR也有的重复文本过滤功能，部分游戏虽然不用特殊码也能提前文本，但提取的文本会出出现现重重复复的情况。

**Comment by luojunyuan** [comment]
临时的解决方案：我个人的操作是关闭隐藏标题栏后，想要再去拖动窗口，先点击一下翻译窗口非标题的空白部位，聚焦窗口，标题栏就不跳动了

关于文本重复请打开text.json的[deduplicate](https://github.com/project-yuki/YUKI/blob/master/docs/ConfigFiles_CN.md#deduplicate)

**Comment by tinyAdapter** [comment]
暂时禁止在可能出现抖动情况下的标题栏拖拽操作了，算是一种解决方案吧（

**Comment by mutouchan** [comment]
> 暂时禁止在可能出现抖动情况下的标题栏拖拽操作了，算是一种解决方案吧（

你好，抖动应该是与是否拖拽标题栏是没有关系的，问题可能出在标题栏、底部栏（含有“翻译”、“文本钩子设置”、“翻译器设置”一栏）的自动隐藏速度太快，以及**背景色透明度设置会影响UI窗口判断范围**（翻译窗口透明度为0、进入“翻译”页面的情况下，**只有鼠标指针移动到文本上，底部栏才会出现**，而非0的情况则正常。设置自动隐藏标题栏的情况同样。）。
这个你可以自己测试一下，把翻译窗口透明度设置为0，加载钩子进入“翻译”页面，观察底部栏还能否点击到。
参考解决方法：
懒狗（）方法1：增加标题栏和底部栏自动隐藏的缓冲时间（如鼠标指针移开几秒后才隐藏）。
懒狗方法2：窗口透明度最低只能设置为1，避免设置为0时窗口范围不再是和标题栏齐宽的矩形而是限定为文本存在范围。

奋斗者方法：翻译器设置窗口和翻译窗口分离，像VNR那样设置窗口和翻译窗口是单独的，这样就不用再自动隐藏标题栏和底部栏导致可能出现错误了。

还有一个请求是，标题栏自动隐藏后的文本位置变化能否避免，经观察，标题栏自动隐藏后，翻译文本会随着标题栏的隐藏而向上升高了一行。
