### ISSUE TITLE
美少女万华镜4无法获取文本

### ISSUE THREAD

**Issue by meomeoneko9** [project-yuki/YUKI#72]
yuki v0.14，游戏版本1.01
不使用特殊码，或者使用网上的两个特殊码/HQ-4@696694 1.01版 /HQ-4@69645C都不能获取游戏内文本
如果先启动游戏在翻译窗口使用特殊码，会弹出错误提示
![biman04_yuki](https://user-images.githubusercontent.com/60308822/74711207-6568ec80-525e-11ea-9a70-3465affd5aee.png)
另外有时候不小心关掉翻译小窗口找不到打开它的地方，只能全部退出重开
以下是调试信息，貌似复制不了？
![11111](https://user-images.githubusercontent.com/60308822/74711738-ad3c4380-525f-11ea-9855-04969b9e2572.PNG)

**Comment by meomeoneko9** [comment]
上个问题已经自己解决，原因是textractor缺少dll没启动成功。自己去运行一下TextractorCLI.exe看缺什么dll下载回来扔进去就行
但是现在又有新问题了：全是乱码。据说这个游戏要设置utf-16编码才可以正确获取文本，在哪里设置呢……
![11111](https://user-images.githubusercontent.com/60308822/74717786-f5616300-526b-11ea-80bc-3f7a2888c8fd.PNG)

**Comment by luojunyuan** [comment]
Yuki没有设置编码的地方。
textractor所需运行库在[这儿14mb](https://github.com/Artikash/Textractor/releases/download/v4.9.1/vcredist-x86.exe) ，可否先删除你加入的dll文件，安装该运行库后再运行试试？
或者尝试更改游戏字体，看看会不会有变化。（个人经验）

**Comment by tinyAdapter** [comment]
> 上个问题已经自己解决，原因是textractor缺少dll没启动成功。自己去运行一下TextractorCLI.exe看缺什么dll下载回来扔进去就行
> 但是现在又有新问题了：全是乱码。据说这个游戏要设置utf-16编码才可以正确获取文本，在哪里设置呢……
> ![11111](https://user-images.githubusercontent.com/60308822/74717786-f5616300-526b-11ea-80bc-3f7a2888c8fd.PNG)

这个问题只有部分人会遇到，很迷，不知道为什么。你可以试试 https://github.com/project-yuki/YUKI/issues/66#issuecomment-586674582 看能不能解决

**Comment by meomeoneko9** [comment]
mecab各种编译都试了一遍，全部乱码……关闭mecab以后好了，非常感谢！
