### ISSUE TITLE
获取文本会出现重复现象

### ISSUE THREAD

**Issue by sekurodesu** [project-yuki/YUKI#74]
如题，在文本钩子设置的时候，获取到的文本都是会出现一个字多次重复的现象，大佬能不能做一个和VNR一样的去重的功能呢？
还有个小建议就是能不能做一个VNR那种可以让翻译背景变成透明的功能，这样不会遮挡游戏画面

**Comment by luojunyuan** [comment]
这俩个问题现在都可以手动改一下设置文件夹目录里的文件解决
1. 关于文本重复请打开config\text.json的[deduplicate](https://github.com/project-yuki/YUKI/blob/master/docs/ConfigFiles_CN.md#deduplicate) （即设置为true）
2. 背景透明在config\gui.json中设置 `"renderMode": "transparent"`
