### ISSUE TITLE
询问

### ISSUE THREAD

**Issue by 2017KoriMiyohashi** [project-yuki/YUKI#76]
请问一下怎么修改翻译后的文字单行长度，有些文本长一些就自动换行了。当翻译框覆盖在游戏文字框上面时文本一长位于下面的翻译结果就会被挤出屏幕外面。

**Comment by tinyAdapter** [comment]
文字长度是跟着窗口宽度走的，你可以选择把翻译窗口拉长或者在设置页面把翻译文字大小改小一些
