### ISSUE TITLE
关于软件的一些小问题，还请作者来解答下，感谢了

### ISSUE THREAD

**Issue by kannohaminami** [project-yuki/YUKI#77]
1.按照D:\LE\LEProc.exe" -run %GAME_PATH%运行，会提示游戏运行失败，参考调试信息
2.怎样才能全透明啊，现在的全透明自带毛玻璃效果
3.游戏玩着玩着会弹出a javascript error occurred in the main process,这个怎么解决啊.
希望作者能帮我解决下这些问题，感谢了

**Comment by tinyAdapter** [comment]
问题1如果你没复制错的话，最左边缺了一个引号（"）

问题2看最新的[说明](https://github.com/project-yuki/YUKI/blob/b0.14.1/docs/FAQ_CN.md#%E7%BF%BB%E8%AF%91%E7%AA%97%E5%8F%A3%E6%9C%89%E4%B8%80%E5%B1%82%E6%AF%9B%E7%8E%BB%E7%92%83%E6%95%88%E6%9E%9C%E6%80%8E%E6%A0%B7%E5%8E%BB%E9%99%A4)

问题3不好复现，最好能给一下截图和出现错误时的调试信息

**Comment by kannohaminami** [comment]
![-2d0ada7861a2bf16](https://user-images.githubusercontent.com/61228273/74830908-21a1e000-534f-11ea-94ec-024f653050d5.png)
![-7c3d0ab9449bdb7f](https://user-images.githubusercontent.com/61228273/74830915-25356700-534f-11ea-9a4f-cfd6a3447ca4.png)


还是进不去

**Comment by tinyAdapter** [comment]
直接在命令行运行`"D:\LE\LEProc.exe" -run "D:\amatsutsumi\amatsutsumi\cmvs32.exe"`看看结果是啥

**Comment by kannohaminami** [comment]
运行了出现了这个，![-56afcede8e3d4c0f](https://user-images.githubusercontent.com/61228273/74832212-bf96aa00-5351-11ea-94ea-37920d7032c3.png)
刚才的第三个问题也是弹出的这种类似的

**Comment by tinyAdapter** [comment]
那问题3就是因为问题1导致的，你的游戏没有实际运行起来，Textractor找不到进程注入

我没有看见`"D:\LE\LEProc.exe" -run "D:\amatsutsumi\amatsutsumi\cmvs32.exe"`的运行结果，我的意思是在cmd里运行这行命令，然后应该会给一个错误提示

**Comment by kannohaminami** [comment]
![63de119175f145c3](https://user-images.githubusercontent.com/61228273/74832638-ba862a80-5352-11ea-93ba-5ac98c871259.png)
运行了，什么也没发生

**Comment by tinyAdapter** [comment]
那可能是游戏有问题，闪退了。这个就是游戏本身的问题了ㄟ( ▔, ▔ )ㄏ

**Comment by kannohaminami** [comment]
好吧，感谢了

**Comment by luojunyuan** [comment]
建议你尝试设置`"D:\LE\LEProc.exe" %GAME_PATH%`
这是我的设置：
![image](https://user-images.githubusercontent.com/28323948/74833917-629cf300-5355-11ea-851a-7c7ce24332eb.png)
![image](https://user-images.githubusercontent.com/28323948/74834020-91b36480-5355-11ea-82ed-822e4a0fb2db.png)
再不济你先设置游戏启动方式为no changer，看看不转去能否直接启动游戏

**Comment by kannohaminami** [comment]
试过了，还是不行，估计是游戏问题，我玩的是紫社天津罪。
感谢你的解答了。no changer是可以的，我只是想试试转区，毕竟标题乱码看着挺不爽的，只能将就玩了

**Comment by luojunyuan** [comment]
> 试过了，还是不行，估计是游戏问题，我玩的是紫社天津罪。
> 感谢你的解答了。no changer是可以的，我只是想试试转区，毕竟标题乱码看着挺不爽的，只能将就玩了

你看我截图，我也在玩天津罪。
我也是用LE启动的，你是否有尝试把-run参数去掉？

**Comment by kannohaminami** [comment]
老实说你的截图我点不开，不知道什么情况。。。。。。
