### ISSUE TITLE
钩子只能选取一个，但文本会在不同钩子上更新

### ISSUE THREAD

**Issue by fufu-cn** [project-yuki/YUKI#82]
![image](https://user-images.githubusercontent.com/61412570/75223496-893dac80-57e1-11ea-9005-2ac69fc7eb89.png)
有两个名称相同的钩子，但文本有时候在一个钩子上更新，有时候又换成另一个了
我注意到vnr的解决办法是可以设置主要文本和次要文本
能不能改成可以同时选取多个钩子？
游戏是 まほ×ろば -Witches spiritual home

**Comment by luojunyuan** [comment]
尝试加载钩子 `HWN-4@83AAB:mahoXroba.exe` 试试看？

**Comment by luojunyuan** [comment]
![image](https://user-images.githubusercontent.com/28323948/75227583-67e0be80-57e9-11ea-964a-466ca47ebeef.png)
我发现yuki自己本身便可以正常获取到文本，你为啥还要自己输入一个呢

**Comment by fufu-cn** [comment]
> ![image](https://user-images.githubusercontent.com/28323948/75227583-67e0be80-57e9-11ea-964a-466ca47ebeef.png)
> 我发现yuki自己本身便可以正常获取到文本，你为啥还要自己输入一个呢

我明白了，我之前用的认证回避没法直接读取，现在换了一个其他版本的就可以了
