### ISSUE TITLE
建议（希望）增加翻译后文本的单行显示长度

### ISSUE THREAD

**Issue by 2017KoriMiyohashi** [project-yuki/YUKI#83]
![Screenshot_202](https://user-images.githubusercontent.com/42110767/75262262-3686e380-5827-11ea-9e84-e46e52090293.png)
目前我的显示设置是2560*1440 100%缩放比，翻译后的文本显示区域仍然很小希望能够增加翻译后文本的单行显示长度。希望能够在黄色方框区域显示翻译器名，白色区域显示翻译结果

**Comment by tinyAdapter** [comment]
这部分跟CSS有关，当时我随便照着自己的显示器调了调没在意，等我之后再重新写一下

**Comment by 2017KoriMiyohashi** [comment]
谢谢

**Comment by tinyAdapter** [comment]
v0.14.2已修复
