### ISSUE TITLE
打开自动隐藏标签栏后, 在翻译界面触屏 yuki galgame translator 整个界面布局闪烁, 无法移动

### ISSUE THREAD

**Issue by yinggcy** [project-yuki/YUKI#88]
windows 10,  4k屏
![gifhome_1920x1080_8s (4) (1) (1)](https://user-images.githubusercontent.com/31366576/75948885-9ba19f80-5edf-11ea-8555-3ff8b1250a10.gif)

**Comment by CPCer** [comment]
在鼠标移动到附近位置时，偶尔也有类似问题

**Comment by tinyAdapter** [comment]
参照 #71
