### ISSUE TITLE
建议: 为每个游戏记录钩子设置

### ISSUE THREAD

**Issue by yinggcy** [project-yuki/YUKI#91]

**Comment by rxia24** [comment]
![image](https://user-images.githubusercontent.com/22437401/76492494-59daa100-646b-11ea-9b8c-d454165a541a.png)
这里可以输入游戏的钩子

**Comment by yinggcy** [comment]
> ![image](https://user-images.githubusercontent.com/22437401/76492494-59daa100-646b-11ea-9b8c-d454165a541a.png)
> 这里可以输入游戏的钩子

/HWNX0@5F2A4:mono.dll   是这样输吧
但没有效果, 翻译界面什么都没有, 文本钩子那栏也不会更新钩子了

**Comment by luojunyuan** [comment]
> > ![image](https://user-images.githubusercontent.com/22437401/76492494-59daa100-646b-11ea-9b8c-d454165a541a.png)
> > 这里可以输入游戏的钩子
> 
> /HWNX0@5F2A4:mono.dll 是这样输吧
> 但没有效果, 翻译界面什么都没有, 文本钩子那栏也不会更新钩子了

不输入特殊码文本钩子栏目也不会更新钩子吗？
其实也可以尝试在文本钩子那栏输入
在游戏卡片上主要是记录保存用

**Comment by yinggcy** [comment]
> 不输入特殊码文本钩子栏目也不会更新钩子吗？
> 其实也可以尝试在文本钩子那栏输入
> 在游戏卡片上主要是记录保存用

不输入特殊码, 翻译窗口的文本钩子设置那栏会正常更新

**Comment by luojunyuan** [comment]
你可以先进入游戏，再在钩子窗口输入特殊码，仔细看console返回的英文，若提示inject errror的字眼，说明你的hcode有问题

**Comment by yinggcy** [comment]
> 你可以先进入游戏，再在钩子窗口输入特殊码，仔细看console返回的英文，若提示inject errror的字眼，说明你的hcode有问题
> 
> 或者你可以单独尝试textractor，我没记错的话unity3d的游戏应该是支持的

![批注 2020-03-19 012147](https://user-images.githubusercontent.com/31366576/76988692-13f86e00-6980-11ea-9970-d91fd5ea63d5.png)

**Comment by luojunyuan** [comment]
> > 你可以先进入游戏，再在钩子窗口输入特殊码，仔细看console返回的英文，若提示inject errror的字眼，说明你的hcode有问题
> > 或者你可以单独尝试textractor，我没记错的话unity3d的游戏应该是支持的
> 
> ![批注 2020-03-19 012147](https://user-images.githubusercontent.com/31366576/76988692-13f86e00-6980-11ea-9970-d91fd5ea63d5.png)

不好意思，没看明白你是什么意思。我从背景图图里看到mono的钩子已经自动注入了。你为什么还要手动输入一遍相同的特殊码呢？

**Comment by yinggcy** [comment]
> 不好意思，我没看明白你是什么意思。我从背景图图里看到mono的钩子已经自动注入了。你为什么还要手动输入一遍相同的特殊码呢？

额, 我不知道不可以这样, 我这样做为了说明特殊码就是从那个获得的, 不会是错的. 下面是在游戏卡片上输入特殊码后的情况, 测试了几个游戏都这样, 特殊码用的是文本钩子设置里的.
![批注 2020-03-19 092304](https://user-images.githubusercontent.com/31366576/77022027-6e66ee00-69c3-11ea-8764-d46c1cd5c11f.png)

![批注 2020-03-19 091423](https://user-images.githubusercontent.com/31366576/77021591-1d0a2f00-69c2-11ea-8356-f0ba61babc7d.png)
![批注 2020-03-19 091443](https://user-images.githubusercontent.com/31366576/77021595-1f6c8900-69c2-11ea-99b3-5516110d83d4.png)

**Comment by luojunyuan** [comment]
textractor自动生成的特殊码并不一定适用于手动输入。建议寻找其他的特殊码

**Comment by yinggcy** [comment]
> textractor自动生成的特殊码并不一定适用于手动输入。建议寻找其他的特殊码

哦, 这样啊, 谢谢了
