### ISSUE TITLE
如图，请问一下js报错怎么解决

### ISSUE THREAD

**Issue by flyygph** [project-yuki/YUKI#93]
![QQ截图20200309202802](https://user-images.githubusercontent.com/42086066/76215038-da6d8780-6248-11ea-8603-abce182a1c10.png)
直接通过进程启动报错，无法弹出翻译框，添加启动虽然不报错也没有翻译框

**Comment by chinsan996** [comment]
+1

**Comment by luojunyuan** [comment]
> +1

可以将调试日志中的内容复制上来看一下吗
调试日志在这里↓
![image](https://user-images.githubusercontent.com/28323948/76754722-8c630180-67bd-11ea-848f-5dfcc8d81d23.png)

**Comment by chinsan996** [comment]
> > +1
> 
> 可以将调试日志中的内容复制上来看一下吗
> 调试日志在这里↓
> ![image](https://user-images.githubusercontent.com/28323948/76754722-8c630180-67bd-11ea-848f-5dfcc8d81d23.png)

解决了，可能le设置有点问题
