### ISSUE TITLE
启用灵格斯后点击分词无翻译

### ISSUE THREAD

**Issue by xinghe27** [project-yuki/YUKI#94]
**前提**：使用的版本是minori v0.14.1，转换器使用localEmulator，以管理员方式启动，已经配置了Mecab路径，完成了分词，已下载了github中提供的字典库，并解压后链接到yuki中。Mecab和字典库都已启动并保存后重启过YUKI。

**问题**：点击分词后的日语单词弹出蓝框，无翻译内容。查看了调试信息，在点击单词后没有输出，不知道是否有问题。。

<img src="https://raw.githubusercontent.com/xinghe27/images/master/yuki/QQ%E6%88%AA%E5%9B%BE20200310101216.png" style="max-width:100%;"></img>

<img src="https://raw.githubusercontent.com/xinghe27/images/master/yuki/QQ%E6%88%AA%E5%9B%BE20200310101448.png" style="max-width:100%;"></img>

<img src="https://raw.githubusercontent.com/xinghe27/images/master/yuki/QQ%E6%88%AA%E5%9B%BE20200310110916.png" style="max-width:100%;"></img>

**Comment by rxia24** [comment]
试着用”管理员身份运行“打开YUKI

**Comment by xinghe27** [comment]
> 试着用”管理员身份运行“打开YUKI

试过了，没有用

**Comment by rxia24** [comment]
那就奇怪了，尝试用这里的Mecab？[Link](https://github.com/project-yuki/libraries/tree/master/dict/lingoes)
灵格斯词典大小是否为129MB？

**Comment by xinghe27** [comment]
> 那就奇怪了，尝试用这里的Mecab？[Link](https://github.com/project-yuki/libraries/tree/master/dict/lingoes)
> 灵格斯词典大小是否为129MB？

太感谢了，可能是之前解压问题，看了下词典大小不一样，重新下载覆盖后可以了。
