### ISSUE TITLE
启用「谷歌翻译」把日文翻为英文的字串输出问题

### ISSUE THREAD

**Issue by kalestorm123** [project-yuki/YUKI#95]
我开启「谷歌翻译」的API，翻译语种从zh-CN改为en。

结果双引号" 会输出成字串&quot附加分号，单引号' 会输出成字串&#39附加分号，如下图所显示，请问该怎样解决？

版本是YUKI minori v0.14.1，有配置区域转换器localEmulator，执行日语编码的游戏。

更新： 我又试了 AZURE API 从日文翻成英文，不会出现同样情况。另外換了別的遊戲試試，不管開不開localEmulator 都會變成&quot附加分号。

![image](https://i.imgur.com/8D7Wbkw.jpg)

**Comment by kalestorm123** [comment]
補充： 我後來試了 AZURE API 日文翻成英文不會出現同樣情況

**Comment by tinyAdapter** [comment]
我大概猜得到原因在哪里，只有谷歌的API是直接解析HTML得到的，而HTML中对于这些符号都是要进行转义的

下一版应该会修复

**Comment by tinyAdapter** [comment]
v0.14.2已修复
